### ISSUE TITLE
Need a new symbol for hierarchical parts

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-visual-deprecated#14]
The user-defined symbol is associated with "engineered region" or similar SO term.  It is used typically to represent a composition of multiple sub-components in hierarchical designs, so this term is appropriate.

There is currently no symbol available for generic SO term.  Namely, we need a symbol for objects representing SO terms that do not currently have any visual glyph.

**Comment by jakebeal** [comment]
Actually, under SBOL Visual 1.0.0 the user-defined symbol is not associated with any SO term.
The .obo files created also do not associate it with any SO term.

In my current draft of the SBOL Visual 2.0.0 specification, I am proposing to associate it with SO:0000110 (Sequence Feature).  I also thought about associating it with SO:0000001 (Region), but thought that would be too restrictive, since there may also be zero-length features people want to represent that aren't included in the feature set.

Would that definition be sufficient for your purposes?

**Comment by cjmyers** [comment]
Yes, but I would then flip my request and state that I need a symbol for composite “engineered” objects.  This one symbol is serving two duties, so I believe we really need two symbols, since these are different use cases.

**Comment by jakebeal** [comment]
Can you please give a concrete example (preferably visual in nature), to make it clear what you're looking for, and why it needs to be different from the generic symbol?

**Comment by cjmyers** [comment]
I’m thinking from more a UI standpoint.  This issue came up recently in the development of SBOL Designer.  In that tool, when instantiate a glyph, you are given the option to refine the role to a more specific term.  In the current version, the user-defined roles are engineered region and everything descendent from that.  This is good when what the user-defined is used for is a hierarchical composition of engineered components.  However, if all you want to do is add an SO term that does not have a defined glyph, this is different, and the roles the user should be presented with are all SO terms from Sequence Feature (a much longer list).  

So, having two glyphs allow the role choices to be refined appropriately based on the intent.  Furthermore, from a visual standpoint, the “hierarchical” glyph tells you that there is likely underlying structure.  The “generic” glyph tell you that it is simply a component for which we do not yet have a specific glyph.  They give very different visual clues.

Something as a simple as a filled square for one of them might do the trick.

**Comment by jakebeal** [comment]
This sounds like a differentiation best made in the tool using the visual properties reserved for just such use, such as fill color and line style.

I would suggest using the prototypical solid lines and white box for the "no specified glyph" case, and use something like a filled grey box for the hierarchical region.  Note, however, that you may wish to allow a hierarchical region to be defined using other symbols as well: for example, a whole hierarchical complexity can often underly the design of a single synthetic promoter --- see for example the design of CRP and CRU6 promoters in http://jakebeal.com/Publications/KianiBeal-CRISPR-NatureMethods-2014.pdf

**Comment by cjmyers** [comment]
I don't think you should close this with so little discussion.

**Comment by cjmyers** [comment]
I still believe that this visual difference should be standardized.  To me, these are very different things.  The glyphs are associated with SO term branches, and having a glyph associated with engineered region and below is important to have as a separate glyph.  

However, since this would be restricted to that branch, this necessitates having a separate glyph for “generic feature”.  I know I’m repeating myself, so I think perhaps we need to take this to a wider audience as we clearly disagree on this.

> I would suggest using the prototypical solid lines and white box for the "no specified glyph" case, and use something like a filled grey box for the hierarchical region. Note, however, that you may wish to allow a hierarchical region to be defined using other symbols as well: for example, a whole hierarchical complexity can often underly the design of a single synthetic promoter --- see for example the design of CRP and CRU6 promoters in http://jakebeal.com/Publications/KianiBeal-CRISPR-NatureMethods-2014.pdf <http://jakebeal.com/Publications/KianiBeal-CRISPR-NatureMethods-2014.pdf>
This is indeed allowed in SBOLDesigner.  You can have sub-structure to any glyph.  The difference though is that a promoter with sub-structure from a behavioral standpoint still behaves like a promoter.  You do not need to look at the sub-structure to understand its basic behavior.  The difference for a hierarchical glyph is that it says it is an engineered region of perhaps multiple functions (maybe RBS + CDS).  You need to dive into to see its parts and infer its set of functions.

**Comment by jakebeal** [comment]
You're correct: I still don't understand why this distinction needs a new symbol.

So far as I can see, your "engineered region" is just an object with a behavior that we don't have a symbol for right now.  For example, you might have an "engineered region" which is one of Chris Voigt's NOR gates.  At present, we don't have a glyph for a Voigt-style NOR gate, but if they become widespread then in the future we might, at which point we'd simply swap in the glyph.

Complementarily, just because a region's description is complex and hierarchical doesn't mean it's necessarily "engineered."  For example, we might include the whole Shewanella Mtr pathway into a system as a unit.  That complex gene cluster might still be the original natural sequence, and is both complex and well understood enough that it might be best described hierarchically.

Thus, I see this as making a distinction that is invalid in both directions.

**Comment by cjmyers** [comment]
Started a SBOL-visual topic, since I don’t think many people are watching the tracker.  Maybe want to move discussion there.

> So far as I can see, your "engineered region" is just an object with a behavior that we don't have a symbol for right now. For example, you might have an "engineered region" which is one of Chris Voigt's NOR gates. At present, we don't have a glyph for a Voigt-style NOR gate, but if they become widespread then in the future we might, at which point we'd simply swap in the glyph.
> 
It would no longer be an engineered region at that point, as it would be given its own SO term.
> Complementarily, just because a region's description is complex and hierarchical doesn't mean it's necessarily "engineered." For example, we might include the whole Shewanella Mtr pathway into a system as a unit. That complex gene cluster might still be the original natural sequence, and is both complex and well understood enough that it might be best described hierarchically.
> 
> 
Agree that Engineered is not perhaps the right term when describing existing bio-systems, but since we are talking synthetic biology applications, it is more often than not what we mean.  Namely, we are using a group of components in an engineering (synbio) setting even if we did not design the individual components from first principles, but rather found them in nature.

**Comment by bbartley** [comment]
Hi Chris, Jake,
 I do agree with Chris that having some kind of visual indicator of hierarchical composition is extremely valuable and useful.  Interestingly, the problem Chris is describing also came up when the UW team first started developing SBOLDesigner. At the time, we distinguished between 3 cases:  an unrealized module, a semi-realized module, and a fully-realized module.  An unrealized module contains subcomponents but the subcomponents are not yet specified.  A semi-realized module is one that contains typed subcomponents but no sequence information.  A fully-realized module contains typed subcomponents with sequences specified.  To distinguish these, I proposed a black, gray, or white box (ie, user-defined symbol), respectively.  This scheme has intuitive connotations for an engineer.  However, the SBOLv spec leaves color formatting entirely up to the user, so this proposal was shot down on the mailing list.
Anyway, there are still other ways that we might use visual cues to indicate hierarchical composition, and I think that's a very important topic.
BestBryan

**Comment by jakebeal** [comment]
> An unrealized module contains subcomponents but the subcomponents are not yet specified.  A semi-realized module is one that contains typed subcomponents but no sequence information.  A fully-realized module contains typed subcomponents with sequences specified.  To distinguish these, I proposed a black, gray, or white box (ie, user-defined symbol), respectively.  

Again, my contention is that this sounds to me like we've already got exactly the set of symbols that we need, since you can represent the additional information that you want to show by selecting an appropriate fill.

In another context or another tool, these distinctions are not relevant and would not be desirable to represent.  For example, in BioCompiler, we never specify sequences, so there is no distinction to make.  In a published experimental paper, on the other hand, all of the sequences are certainly fully specified, and so there is no distinction to make there either.  In both of these cases, we'd want to be able to use fill to represent other types of information.

**Comment by bbartley** [comment]
That's fine.  However, sometimes we need to indicate hierarchical composition in hand-drawn diagrams, too, so it's not just a UI issue.  I'm not stuck on any one solution, just simply stating that SBOL Visual ought to have some kind of convention for signifying hierarchy.  It's such an important concept in the data model, as well, it feels slightly incoherent to me that SBOL Visual does not address hierarchical composition.  IMHO.

**Comment by drdozer** [comment]
I keep wanting this. There's a big difference, cognitively, between a user-defined part on the one hand and an entire sub-design on the other. If I have a composite design made by gluing 3 biobricks together then at one level of abstraction I have 3 biobrick regions that have rich internal structure at another. This is obviously a very different beast cognitively to, for example, using user-defined to represent regions critical to a crispr design in the absence of specific visual iconography for crisprs.

**Comment by jakebeal** [comment]
Interestingly, there is no formal symbol for "subsystem" in electronics diagrams either.  Now, that doesn't mean we can't make one, and I'm quite open to seeing a compelling proposal.  I'm just not convinced that a compelling case and good associated symbol exists, and in the meantime "user defined" serves adequately for both cases, meaning that I see this as a "nice to have" rather than a critical path issue.

**Comment by drdozer** [comment]
I really quite strongly don't think that user-defined can possibly serve both, because, as I've said, the two cases are cognitively distinct.

Take the case of a plasmid with and without a payload inserted. You often don't want to show the content of the payload. However, you do want to tell the user if this plasmid does or doesn't have the payload in it, and if it does, draw something in the payload site that tells the biologist that there's a payload here that has interesting internal structure. Drawing a user-defined box there makes it look like instead of a payload, you have a part of unspecified biological function. While that it sort of true at the biochemical level, it isn't at all the intent at the cognitive level, and these diagrams are for people to communicate with people so the cognitive level is always the important level.

**Comment by jakebeal** [comment]
I would represent this case with a label on the user-defined that says: "payload"

**Comment by bbartley** [comment]
Another approach for indicating hierarchical composition that I have contemplated is using some kind of an accent mark (eg, a caret) over or under a glyph to suggest the component contains substructure.  This translates equally well for user-defined or explicit components (eg, promoter).  It is simple to draw by hand and would make sense in a UI.  Also it would lend a "linguistic" flavor to SBOLv.

**Comment by cjmyers** [comment]
Changed title to indicate that the new symbol is actually being proposed for the hierarchical objects rather than the "other" SO terms.

**Comment by cjmyers** [comment]
Ok, below is a concrete example of the problem we face in designer.  In the first screenshot, the User-defined symbol is used for hierarchy to indicate an “Engineered Region” that has multiple functions (i.e., an RBS and CDS). 

In the second screenshot, we see a file converted from GenBank.  Here the user-defined shows up because there are several features in the GenBank file that do not map to glyphs in SBOL Visual.

To me, these are fundamentally different from both a visualization perspective and UI perspective.  In one case, the visualization is telling you there is more details that are hidden while in the other it is telling you that there are parts that you don’t know how to render in a specific way.  These are simply different messages and using one image to convey both messages is confusing.

**Comment by jakebeal** [comment]
Chris: the referenced images don't seem to be attached or linked.

**Comment by jakebeal** [comment]
Brian: can you link an example of a proposed accent mark like this?

**Comment by cjmyers** [comment]
Perhaps github does not do attachments.  I’ve resent to sbol-visual list.

**Comment by jakebeal** [comment]
Handled in SEP V009 https://github.com/SynBioDex/SBOL-visual/issues/16
